services:
    arc_web_api:
        build:
            context: .
            target: development
        ports:
            - "5001:5001"
        depends_on:
            arc_mysql_db:
                condition: service_healthy
            arc_rabbit_mq:
                condition: service_started
            arc_redis_stack:
                condition: service_started
        environment:
            DATABASE__HOST: "arc_mysql_db"
            DATABASE__PORT: "3307"
            DATABASE__NAME: "arc_db"
            DATABASE__USER: "root"
            DATABASE__PASSWORD: "qwerty"
        container_name: arc_web_api_img
    arc_mysql_db:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "TRUE"
            MYSQL_DATABASE: "arc_db"
        container_name: arc_mysql_db_img
        healthcheck:
            test: mysqladmin ping
            start_period: 2s
            interval: 5s
            timeout: 15s
            retries: 5
    arc_rabbit_mq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        container_name: arc_rabbit_mq_img
    arc_redis_stack:
        image: redis/redis-stack
        ports:
            - "6379:6379"
        container_name: arc_redis_stack_img